image:
  file: .gitpod.dockerfile
tasks:
  - command: mkdir /home/gitpod/.aws
  - command: echo '[default]'>>/home/gitpod/.aws/credentials
  - command: echo "aws_access_key_id=$AccessKeyId">>/home/gitpod/.aws/credentials
  - command: echo "aws_secret_access_key=$SecretKey">>/home/gitpod/.aws/credentials