image:
  file: .gitpod.dockerfile
  - command: echo '[default]'>>.aws/credentials
  - command: echo 'aws_access_key_id=$AccessKeyId'>>.aws/credentials
  - command: echo 'aws_secret_access_key=$SecretKey'>>.aws/credentials